omnibus_build.sh
to make sure to update to the latest version of omnibus-software
=> Add a bundle update step

config/software/datadog-agent.rb
See https://github.com/DataDog/dd-agent/pull/1422
=> Ship the new utils directory for flare

Vagrantfile, config/projects/datadog-agent.rb
See https://github.com/DataDog/omnibus-ruby/pull/3
=> build_version method for stable/nightly builds

config/projects/datadog-agent.rb, config/software/datadog-agent.rb, package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/postrm, package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
Everything is in the title. Careful there's also a modification on
install_agent.sh in the dd-agent project.
=> [systemd] made the agent systemd compliant

Gemfile, config/projects/datadog-agent.rb, config/software/datadog-agent.rb, package-scripts/datadog-agent/postinst
And also run rubocop.
See https://github.com/DataDog/dd-agent/pull/1569
=> [core] add /run directory

package-scripts/datadog-agent/postinst
=> [core] fix internal /run rights

Gemfile, omnibus_build.sh
A release branch is forked from master on omnibus-software repository
for each major and minor release. Use it instead of master.
=> [deps] use omnibus-software agent release branch

Gemfile
Instead of the experimental ones we were working on
=> Use stable Omnibus-4 branches of our forks

package-scripts/datadog-agent/postinst
Addresses https://github.com/DataDog/dd-agent/issues/1587
=> Check for dd-agent user before creating it

package-scripts/datadog-agent/postinst
Add some echo messages and the correct error flags for capturing `dd-agent` user existence
=> [postinst][deb] Add error flags

config/projects/datadog-agent.rb
=> Get rid of dd agent format

Gemfile
Completes the upgrade to omnibus 5
=> Use omnibus 5 branch of omnibus-ruby

DEPENDENCY_TREE.txt, config/projects/datadog-agent.rb, omnibus_build.sh
Add `go-metro` dependencies to build system.
=> [integrations] go-metro

config/projects/datadog-agent.rb, config/software/datadog-agent.rb
Related to https://github.com/DataDog/dd-agent/pull/2313
=> [go-metro] Only include on 64-bit builds

package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/postrm
No changes on the agent files' ownership/permissions for now (will be taken care of for 5.9.0).
Fixes https://github.com/DataDog/dd-agent/issues/1794
=> [deb] Create dd-agent group in postinst script

Rakefile.rb, resources/datadog-integrations/project.rb.erb, resources/datadog-integrations/software.rb.erb, resources/datadog-integrations/validate_manifest.rb
This PR will update the Integration SDK.
Primarily it updates integration to require the datadog-agent as a dependency, and it updates the install_dir.
This will probably include more as the integration build pipeline gets more advanced, and I'll update this description as it includes more.
=> Integration SDK

config/projects/datadog-agent.rb, config/software/datadog-agent.rb, lib/ostools.rb, omnibus_build.sh, package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/postrm, package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
This will allow us to build SUSE Enterprise packages.
=> Adds SUSE Enterprise support

config/software/datadog-agent.rb
I made a small mistake in condensing the debian and suse logic. This fixes it.
=> [Debian][SUSE] Fixes a small mistake in the suse/debian logic

config/projects/datadog-agent.rb, config/software/datadog-agent-integrations.rb, config/software/datadog-agent.rb, omnibus_build.sh, resources/datadog-integrations/software.rb.erb
This changes the logic of the build to ensure that the integrations are built from the integration sdk repo and not from the dd-agent repo.
=> Pulls in checks from the integration core repo

resources/datadog-integrations/software.rb.erb
I left a few things in the individual integrations packages when I fixed their counterparts in the agent package. This should fix them there, too.
=> Fixes individual integrations packages

config/software/datadog-agent-integrations.rb
I made a syntax error that confused the order of operations. This will rectify that
=> fixes syntax error

config/projects/datadog-agent.rb
Sure, explanation is there: https://github.com/DataDog/dd-agent/pull/3224
=> [mac] do not build datadog-gohai

resources/datadog-integrations/validate_manifest.rb
This has some refactoring, but generally this just adds a 1.0.0 validator to validate manifest
=> adds a 1.0.0 validator to validate manifest

README.md, config/projects/datadog-agent.rb, config/software/datadog-process-agent.rb
Re-do of https://github.com/DataDog/dd-agent-omnibus/pull/181
=> Revert "Revert "Add datadog-process-agent to build" (#183)"

config/projects/datadog-agent.rb
Reverts DataDog/dd-agent-omnibus#188
=> Revert "Adding gnupg and dirmngr to allow install on debian 9"

config/software/integration-deps.rb
This is needed for the nfsiostat Pull Request: DataDog/integrations-core#720
This also requires https://github.com/DataDog/omnibus-software/pull/162 to be merged
=> adds nfsiostat

.gitlab-ci.yml, Rakefile.rb, int-sdk.bat, int-sdkver.bat, load-omnibus-toolchain.bat
This change enabled building of the individual check packages on gitlab (for windows).
=> [windows] initial revision; build integrations via gitlab

.gitlab-ci.yml, Rakefile.rb, resources/datadog-agent/msi/source.wxs.erb, resources/datadog-integrations/project.rb.erb
Set the file permissions to datadog.conf to only be readable by administrators and local system
=> Modify permissions on programdata

config/software/datadog-agent-integrations.rb
For now we have remove linux support for sqlserver.
=> Remove unixodbc

config/software/datadog-agent-integrations.rb
After berks update on the dd-agent-builder, it seems like the globs are now evaluated at a different stage during the omnibus run (before the actual wheels are built). To make things worse, windows shell doesn't support wildcards properly - definitely not on omnibus. So nasty workaround: straight up install with python.
=> [windows] fix integrations build on windows

config/software/datadog-trace-agent.rb
Matches new changes from https://github.com/DataDog/datadog-trace-agent/pull/369
=> config/software: update datadog-trace-agent build steps

release.json
Adding version 5.25.3-rc.1 to the release.json
=> Adding version 5.25.3-rc.1 to the release.json

config/software/datadog-agent-integrations.rb
Omnibus build is broken after DataDog/integrations-core#2331
=> Fix omnibus build

config/software/datadog-agent-integrations.rb
Sister PR: https://github.com/DataDog/omnibus-software/pull/220
=> [kerberos] add library support for requiring integrations

config/software/datadog-agent-integrations.rb, lib/integration_whitelist.rb, release.json
See https://github.com/DataDog/omnibus-software/pull/294
=> Add datadog-vsphere integration

release.json
Release final artifacts for 5.32.2
Also removes 5.32.2-rcX
=> [release] add release target 5.32.2

config/projects/datadog-agent.rb
Use SSM-based signing certificate.
=> Use new syntax for signing from file/pass pulled from ssm

release.json
Depends on https://github.com/DataDog/dd-agent/pull/3865
=> Bump nightly version

release.json
=> Add 5.32.6-rc.1 in release.json

release.json
Addagent 5.32.6 to release.json
=> Add agent 5.32.6 to release.json

release.json
Update nightly agent version to 5.32.7
=> Update nightly agent version

release.json
Related to https://github.com/DataDog/dd-agent/pull/3908
=> Update nightly version after 5.32.8 release

config/projects/datadog-agent.rb, release.json
This PR adds:
- changes to GPG signing
- adds 5.32.9 release entry to `release.json`
=> [release] 5.32.9 required changes
