DataDog/dd-agent-omnibus

package-scripts/datadog-agent/preinst
Follow the same logic as in the `install_agent.sh` installation script.
Try `lsb_release` command to determine the Linux distribution and 
- If failing try `/etc/issue` should contain the release information
- If still failing, rely on the `/etc/*-release` files
More info:
http://unix.stackexchange.com/questions/92199/how-can-i-reliably-get-the-operating-systems-name
Also see:
https://github.com/DataDog/dd-agent/pull/1322
=> Determine the Linux distribution logic

config/projects/datadog-agent.rb
This is to avoid issues with yum which uninstalls `datadog-agent` when
running `yum remove datadog-agent-base` because `datadog-agent` provides
`datadog-agent-base`
=> Remove `Provides` from package metadata

config/projects/datadog-agent.rb
So we can make sure to always build it without dirtying the cache.
See omnibus cache docs for details
https://github.com/chef/omnibus/blob/master/docs/Build%20Cache.md
=> Gohai should be added at the very end

package-scripts/datadog-agent/preinst
Old datadog agent versions (< december 2012) had `supervisord.conf` located in `/etc/`.
This check gives an unecessary [warning] (https://github.com/DataDog/dd-agent/issues/1575), while we can just drop it.
=> Removed old `supervisord.conf` location support

package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
Bad regression: this new `find` command fails if there is no
`/opt/datadog-agent`, which is the case for a fresh install.
=> Do NOT fail if /opt/datadog-agent does not exist

package-scripts/datadog-agent/preinst
QUICKFIX FOR THE 5.4 RELEASE
Since yum on CentOS doesn't delete the old package files on update,
there may be an /opt/datadog-agent/agent/checks/utils.py file left which
will conflict with modules in our new folder
/opt/datadog-agent/agent/checks/utils/ and stop the agent from starting
Therefore we delete it on upgrade if it's there...
Here's a build of a 06/10/15 `dd-agent` `master` : https://circle-artifacts.com/gh/DataDog/docker-dd-agent-build-rpm-x64/147/artifacts/0/home/ubuntu/docker-dd-agent-build-rpm-x64/pkg/datadog-agent-5.4.0+git.167.95533e5-1.x86_64.rpm
=> [centos5] Delete checks/utils.py to resolve a bug

package-scripts/datadog-agent/postinst
Reverts DataDog/dd-agent-omnibus#40
It's breaking things. Who knows why
=> Revert "Check for dd-agent user before creating it"

package-scripts/datadog-agent/postinst
Was previously set correctly (see https://github.com/DataDog/dd-agent-omnibus/blob/5.4.x/package-scripts/datadog-agent/postinst#L55) but got removed by mistake, which made dd-agent unable to write pid and jmx status files in the run/ directory.
=> [postinst] Set dd-agent as owner of the run/ directory

package-scripts/datadog-agent/preinst
On OS X, Datadog agent does not provide any uninstallation method. Thus,
agent files are not removed before an agent upgrade.
When a file is removed, renamed or moved, the old file remains and may
likely conflict with the new ones.
Delete the entire $INSTALL_DIR/agent directory, not only *.pyc, *.pyo
files.
=> [osx] delete old agent files

config/projects/datadog-agent.rb, config/software/datadog-agent.rb, package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/postrm
The `/usr/bin{dd-agent,dogstatsd,dd-forwarder}` commands haven't worked
anymore since... a big while. I suspect that this is due to a slight
variation in the behaviour of the `extra_package_file` between Omnibus 3
and Omnibus 4 but I didn't really have time to dig more into it.
This fix just moves the creation of these files to the `postinst` script
which fixes the issue in a rather simple way. These same files also get
deleted in the `postrm` script so that these commands simply don't exist
anymore after removing the agent.
=> Fix dd-agent CLI on Linux

config/projects/datadog-agent.rb, config/software/datadog-agent.rb, package-scripts/datadog-agent/README.md, package-scripts/datadog-agent/postrm
The order in with package scripts get executed during updates with YUM
led to an unexpected behaviour. After a couple of minutes of
facepalming, a decent fix has been implemented. There's also a README in
the `package-scripts/datadog-agent` folder that details a bit more how
updates are handled by APT and YUM, and there's a couple of rather
important differences to pay attention to when updating these scripts :)
=> [linux] Fixed dd-agent CLI: Part II

config/projects/datadog-agent.rb
The `dog` and `dogwrap` scripts are shipped in `/opt/datadog-agent/bin/`.
To avoid conflicting with an existing install of datadogpy I haven't linked these scripts to `/usr/bin/` or to any other dir that is in the `PATH` by default, but we could do it if it makes sense.
Requires https://github.com/DataDog/omnibus-software/pull/32
Fixes #3
=> Add datadogpy

config/software/datadog-agent.rb, package-scripts/datadog-agent/prerm
We keep a list of the .pyc/.pyo files so that we can selectively
remove them in the pkg's prerm script.
Fixes #64
=> [python] Remove compiled python files from package

config/projects/datadog-agent.rb, config/software/datadog-agent.rb
We also switch to a different supervisor.conf file because of the
related changes to supervisor.conf introduced by go-metro.
The `grep` on `supervisor.conf` is not necessary anymore (`user=dd-agent` has been removed on the related dd-agent PR).
Related to https://github.com/DataDog/dd-agent/pull/2297
=> Make go-metro Linux-specific

package-scripts/datadog-agent/README.md, package-scripts/datadog-agent/posttrans, package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
With RPM, if we remove the pyc/pyo files in the `prerm` script, when
the package is upgraded, we end up removing the files that are listed
in the `.py_compiled_files.txt` file of the _new_ version of the
package because the files of the new package get copied _before_ the
`prerm` script of the old package is run.
To avoid this, on RPM, we clean the pyc/pyo files in the prerm script
only when the package is removed. When the package is upgraded we do
the cleaning in the preinst script.
Behaviour unchanged for DEBs.
Also, updated docs.
=> [prerm][python] Better handling of the pyc/pyo files removal on RPM

Gemfile
Pin to 8.10.0 because the next version (8.11.1) doesn't require
the correct versions of its dependencies and calls undefined
methods.
Can be reverted as soon as ohai fixes its dependencies.
=> [ruby] Pin ohai version

Gemfile, Rakefile.rb, build_integration.sh, omnibus_build.sh, resources/datadog-integrations/project.rb.erb, resources/datadog-integrations/software.rb.erb, resources/datadog-integrations/validate_manifest.rb
Rebased version of #68:
```
Add a build_integration.sh entry point,
Add logic to package an integration, including some content validation.
```
I just added a default `OMNIBUS_RUBY_BRANCH` in the agent build script.
=> [Integrations] Add commands to package an integration (rebased)

omnibus_build.sh
We need the default branches to be specified in the _environment_
and not only as bash variables, otherwise the defaults don't actually
work
cc @truthbk
=> Correctly set default branches for repos

config/projects/datadog-agent.rb
On RHEL, the `initscripts` pkg contains the system scripts (`/etc/rc.d/init.d/functions`) that the init script of the agent uses (see https://github.com/DataDog/dd-agent/blob/5.8.3/packaging/centos/datadog-agent.init#L43). It's present by default on CentOS 5/6 but not on CentOS 7 so it's worth adding.
This will add `initscripts` to the `Requires:` field of the rpm pkg's spec file (see https://github.com/DataDog/omnibus-ruby/blob/67368bbf966ca9f2e425eda193f81550e2c08cdf/resources/rpm/spec.erb#L33-L35)
=> [rpm] Add runtime dependency on `initscripts` pkg

package-scripts/datadog-agent/preinst
Prepare the GPG keys rotation: at preinst, add the new key to the list
of APT trusted key.
=> [preinst][deb] add new key to APT trusted keys 🔑

package-scripts/datadog-agent/postinst
It's not useful for most users (especially when upgrading), and we ask
the user to run the command itself with the install script. Let's do the
same.
=> [debian] remove configcheck output when upgrading

package-scripts/datadog-agent/postinst
These scripts use `/bin/sh` which doesn't support the `&>` syntax (bash
extension).
http://unix.stackexchange.com/a/80632
=> [linux] correctly silence configcheck

package-scripts/datadog-agent/postinst
It looks like parentheses are needed for the appropriate order of operations.
=> [apt] Only create dd-agent group if it doesn't already exist

package-scripts/datadog-agent/postinst
Makes `dd-agent` user and group own `/opt/datadog-agent` (which is the home directory of `dd-agent`)
Customer request: with this change, sysadmins can give no permissions at all to other users on the `/opt/datadog-agent` directory (required for PCI compliance), and the Agent can still work fine and not break the sysadmins' changes on upgrade.
Tested the install of a local debian build: from scratch and as an upgrade ; both work fine.
Also, on debian, set the home directory of `dd-agent` to
`/opt/datadog-agent` directly on the `adduser` call, for the sake of
brevity.
=> [postinst] Make `dd-agent` user and group own `/opt/datadog-agent`

package-scripts/datadog-agent/postinst
**NB: This deserves a mention in the Agent's CHANGELOG**
Now that all our linux packages create a `dd-agent` gzroup, it makes
sense to use it on all the files already owned by the `dd-agent` user
=> [linux] Make `dd-agent` group of etc, log, and bin files

omnibus_build.sh
Required this to build: https://github.com/DataDog/docker-dd-agent-build-rpm-x64/pull/13
=> [omnibus_build] set -e messing up chdir.

Gemfile
As it is old, and lack some windows support.
=> Remove ohai constraint

Rakefile.rb, resources/datadog-integrations/project.rb.erb, resources/datadog-integrations/software.rb.erb
This started out as a small bug fix and balooned as a found other bugs.
This fixes a small syntax error, first. It removes a few debugging lines, such as when I was ls -l the integrations directory.
It fixes adding the config files, it changes the sdk directory to integrations, rather than 3rd-party, and it makes the pip install more fault tolerant.
Finally, it (hopefully) fixes the license file conflict.
=> fixes integrations

Gemfile, Rakefile.rb
These changes to the rakefile will enable us to build more than one integration at once.
There are three options now:
1. It will build a single integration
1. It will build multiple specified integrations
1. It will build every integration for that platform into separate packages (it uses ohai to figure out what platform it's on)
=> enables building of multiple integrations

config/projects/datadog-agent.rb, config/software/datadog-agent.rb, omnibus_build.sh
preparation is the first step, and by being the first declared, omnibus treats it specially, and will never change its place (it will always be the first to run).
always_build is back: https://github.com/DataDog/omnibus-ruby/pull/34
We can use it instead of the old hack!
See also: https://github.com/DataDog/omnibus-software/pull/104
=> always_build is back

Gemfile
Good news: it's ✅ !
This is an optional dependency of `omnibus`. The reason why we cannot
declare it as a real dependency in our fork is that we want a particular
version, from git. So we have to install it with bundler, which can only
be done in `dd-agent-omnibus`.
=> [windows] add pedump for healthcheck

config/projects/datadog-agent.rb, resources/datadog-agent/msi/bundle.wxs.erb, resources/datadog-agent/msi/source.wxs.erb
Prior versions installed as perUser, which is undesirable.
Set our installation to per machine.
Provide wrapper executable which will uninstall the old (per-user) version and install the new (per-machine) version.  Note that the wrapper executable still needs to be run as the same user as the original install, or the wrapper will fail (but will fail rather than leaving with overlapping installs)
=> Add support for changing per-user to per machine install

config/software/integration-deps.rb
The pip wheel might be Windows-compatible, but our software definition
is not. Let's double test it when we want to ship it.
=> [windows] remove psycopg2 dep

config/software/datadog-agent-integrations.rb
Omnibus essentially runs a file twice. Once at the beginning and one at the end. The second time it parses the file, it only runs Omnibus DSL methods.
In order to run arbitrary dynamic ruby, you have to wrap the code in `block do end`. This does that in the integrations and allows it to work. Otherwise, it would only work with an initialized cache.
=> Dynamic Build Instructions

config/software/datadog-agent-integrations.rb
We build every integration regardless of whether or not it should be built on that platform. We probably should not do that. 
This will skip a check in the loop if the manifest doesn't include the platform it's being built on.
=> skip checks that shouldn't be built on that platform

resources/datadog-agent/msi/source.wxs.erb
Attempt to add the uninstall of the previous version
Install will always try to uninstall old product
code.  However, it will only find the old product code if the old version
was install perMachine, too.
=> [windows][omnibus installer] Create install flag that allows MSI to upgrade even if previous version is found.

.gitignore, package-scripts/datadog-agent/preinst
This line is always annoying when installing the agent:
`find: ‘/opt/datadog-agent/agent’: No such file or directory`
Let's remove it.
=> [preinst] if find fails, do so silently

config/software/datadog-agent-integrations.rb
Currently, if there's a folder in there (for whatever reason) without a manifest file, the build will fail.
We have one in there right now that has this issue. It should not fail, it should assume that it's an invalid check instead and skip to the next one.
=> check if a manifest file exists, if not skip to the next check

config/software/datadog-agent-integrations.rb
Some integrations have requirements that do not install easily through pip on every platform. Let's not talk about why, because I don't know why protobuf won't. I just know it won't. But we can install it with a source file. So, let's use the manifest to say: don't install this from here, use omnibus.
=> only add the requirement if the manifest says to use it

package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/postrm, package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
`/etc/issue` is not a great way to detect OS because people edit it sometimes. Therefore, there need to be other ways to detect the OS. This will bring detection in line with how we do os detection in the dd-agent [install_script](https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/install_agent.sh#L63-L87).
=> Fixes OS Detection

config/software/datadog-agent-integrations.rb
@masci found an issue with the autoconf: https://github.com/DataDog/dd-agent-omnibus/issues/147. This should fix it by changing it to the proper name.
I have tested this and can confirm that it works 😄
=> Fixes autoconf

resources/datadog-agent/msi/source.wxs.erb, resources/datadog-integrations/msi/source.wxs.erb
[int-sdk] Fix installer so that it only removes the integration directory,
not the entire datadog directory
=> [windows] fix installer to write correct registry entries, so directories aren't incorrectly destroyed on uninstall

config/software/datadog-trace-agent.rb
Temp workaround to unblock our rpm build. This build is broken since https://github.com/DataDog/dd-agent-omnibus/pull/148
See https://circleci.com/gh/DataDog/docker-dd-agent-build-rpm-x64/1694 for an example of a build that failed with `go build -a`
cc @galdor: Could you have a look into this and see if there's a better solution?
=> [rpm][trace] Avoid using `go build -a` on CentOS 5

config/software/integration-deps.rb
Only on Windows since an additional dep is required on Linux (see #129)
=> [pyodbc] Add dep to integration-deps

Rakefile.rb
The Linux SDK build currently has a strange error in it: 
```
(echo "<% name="powerdns_recursor" %><% version="1.0.0" %><% build_iteration="1" %><% integrations_repo="integrations-core" %><% guid="ae533b67-a2af-45ce-8e23-235acb3a3893" %><% description="" %>" && cat /dd-age
nt-omnibus/resources/datadog-integrations/project.rb.erb) | erb > /dd-agent-omnibus/config/projects/dd-check-powerdns_recursor.rb
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval': -:1: unexpected fraction part after numeric literal (SyntaxError)
...owerdns_recursor ;  version=1.0.0 ;  build_iteration=1 ;  in...
...                               ^
-:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
...core ;  guid=ae533b67-a2af-45ce-8e23-235acb3a3893 ;  descrip...
... …
```
=> Fixes SDK Building

config/projects/datadog-agent.rb, config/software/agent-deps.rb, config/software/datadog-agent.rb
This step has to be done at the end of the build to ensure it works well, so it makes sense to extract it. Related PR on omnibus-software: https://github.com/DataDog/omnibus-software/pull/130
Also, move `version-manifest` to the very end of the build.
I've run builds against this branch and made sure that the resulting RPM pkg doesn't output errors on removal anymore
=> [python] Extract removal of python-compiled files to separate def

package-scripts/datadog-agent/preinst
The current logic breaks on servers with limited connections to the internet.
Check if the key already exists.  Private Apt mirrors can provide these keys.
Alternatively, check for a proxy and apply it to the apt-key command.
=> [preinst] Check for proxy and prexisting pgp key

resources/datadog-agent/msi/source.wxs.erb, resources/datadog-integrations/msi/source.wxs.erb
version doesn't work.
Had inadvertently removed the allowDowngrades flag, which also makes it possible to install the same version side by side.  
Now can upgrade & downgrade.
=> [windows] Fix check for previous versions, otherwise upgrade of same

config/software/datadog-agent-integrations.rb
Because the psycopg2 upgrade to 2.7.1 broke master.
It is safe for two reasons:
- checks don't (and shouldn't) rely on CLIs to use python modules.
- the default scripts location is #{install_dir}/embedded/bin, and is
added to the path by the diverse init scripts.
And also: use the pip DSL, it's already cross-platform.
=> [datadog-agent-integrations] remove install-script

resources/datadog-agent/msi/bundle.wxs.erb, resources/datadog-agent/msi/source.wxs.erb
There have been a few support issues where the check for the previous, per-user install fails.  Provide a flag to skip that check, to give support a workaround in these specific cases.
This flag is only to be used when it's known that this is a new install.
=> Add flag to allow skipping of the upgrade test

config/software/datadog-agent.rb
Related to https://github.com/DataDog/omnibus-ruby/pull/41
Should finally ensure that we always pull the latest tag that's on the remote even when the cache already has the latest commit. And this should allow us to never clear the cache for tag-related reasons.
=> [datadog-agent] Use option to always fetch tags

Gemfile
We were relying on a fork made by a chef employee. He deleted his repo, making pedump fail, this restores it: https://github.com/chef/omnibus/commit/825d94f957cedb44de025b0b10f7ff007d383d08
=> removes reliance on pedump fork

resources/datadog-integrations/project.rb.erb, resources/datadog-integrations/software.rb.erb
Omnibus doesn't think that the libraries will be there, so it fails the health checks. It shouldn't, though, it should pass them.
=> Whitelists agent files

package-scripts/datadog-agent/postrm, package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
Regression introduced in #146
This fixes the name of the variable (`DISTRIBUTION` instead of `LINUX_DISTRIBUTION`) against which tests are performed to determine what the distribution is. Since `LINUX_DISTRIBUTION` was never set, all the comparisons against it were `false`.
The fix should only affect "exotic" distributions for which the tests on the existence of specific distrib files wasn't enough.
The absence of bug reports since #146 has been merged is probably a sign
that these distributions are not widely used ;)
=> [package-scripts] Fix OS detection for "exotic" distributions

resources/datadog-integrations/project.rb.erb
RPM integration packages are mistakenly marked with a dist tag, this will remove that.
=> RPM should not have dist tag on integrations

Rakefile.rb
rakefile would (before the fix) rm -rf / on linux or rm -rf c:\ on
windows.  Both of which are bad
=> Fix rakefile.  If caller forgets to set INTEGRATIONS_REPO, then the

package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/postrm, package-scripts/datadog-agent/preinst, package-scripts/datadog-agent/prerm
Replace `==` with posix-shell-compliant `=`. Only really affects
Debian/Ubuntu since Centos and Darwin use bash as `/bin/sh`.
=> [pkg-scripts] Fix `==` bashism in tests

config/software/agent-deps.rb, omnibus_build.sh
This PR adds the corresponding dependencies to enable building jmxfetch via omnibus-software as opposed to keeping the jar file in the `dd-agent` repo. It will also allow us to define what JMXfetch branch/tag we wish to include in the build, defaulting to `master` if none is specified.
https://github.com/DataDog/omnibus-software/pull/91
=> [jmxfetch] build jmxfetch via omnibus

config/software/datadog-agent.rb
This PR results in a 3rd copy of the MS runtime DLLs being installed; however, on server 2008, the service fails to start without this (and the other) copies.
=> [windows] duplicate the windows DLLs into the embedded/DLLs path

package-scripts/datadog-agent/postinst
Wasn't breaking anything important, but did cause an error message to
be displayed and broke the friendly "Agent version" message
=> [package-scripts][macos] Fix typo in `config.py` file name

README.md, config/projects/datadog-agent.rb, config/software/datadog-process-agent.rb
Following the release process docs (https://github.com/DataDog/devops/wiki/Process-Agent#dd-agent-release-process) we will be building a statically-linked binary with our own build environment and omnibus will pull it in based on the chosen branch.
cc @shang-wang
=> Add datadog-process-agent to build

Rakefile.rb, resources/datadog-integrations/software.rb.erb
This should fix the integrations issue. It is not a great solution: I would vastly prefer to be able to do ship them with upgraded dependencies. However, this is the solution we have. So, as sad as I am at the moment to give up the dream of shipping updated deps, it's all we can do. 😢
=> do not install pip deps for some integrations

config/projects/datadog-agent.rb
Linked to: https://github.com/DataDog/dd-agent/issues/3397
Debian 9 is missing by default packages to use `apt-key`.
=> Adding gnupg and dirmngr to allow install on debian 9

package-scripts/datadog-agent/postinst
There's no reason for `/usr/bin/dd-agent` to be the `dd-agent` user/group.
=> removes an unneded chown

config/projects/datadog-agent.rb, package-scripts/datadog-agent/preinst
We don't enforce dependency to dirmngr on the .deb package since it's
shared between ubuntu and debian and it's only available in the
'universe' repo in ubuntu <= 14.04.
Packaging for debian and ubuntu will be split in future version of the
agent.
see: https://github.com/DataDog/dd-agent/issues/3397
=> Adding gnupg to allow install on debian 9 and a warning if dirmngr is not installed

resources/datadog-agent/msi/bundle.wxs.erb, resources/datadog-agent/msi/source.wxs.erb
Allows proxy configuration to be configured on the MSI install command line
Requires companion PR https://github.com/DataDog/dd-agent/pull/3470
=> Allow proxy configuration to be specified on the command line.

config/projects/datadog-agent.rb, config/software/datadog-agent.rb, package-scripts/datadog-agent/postinst, package-scripts/datadog-agent/posttrans
Depends on https://github.com/DataDog/dd-agent/pull/3477
* Improves service restart logic in installation scripts: on CentOS instead of restarting the agent service both in `postinst` and `posttrans`, only restart it in `posttrans`, and make sure a `datadog.conf` file is present before doing so.
* Adds a systemd unit file: CentOS versions that use systemd (>= CentOS 7) will use it instead of the `init.d` script for lifecycle commands (start/stop/restart): same unit file and bash script as what's already used on debian.
On a customer's environment with CentOS 7, using a systemd unit file has been way more reliable than relying on systemd's conversion of the `init.d` script, so let's ship it with the regular RPM pkg. 
These changes pass `dd-agent-testing`. I haven't done much manual testing …
=> [centos] Improve systemd and service restart behaviors

package-scripts/datadog-agent/prerm
On CentOS, stop the agent service in `prerm` script.
Read through https://github.com/DataDog/dd-agent-omnibus/tree/master/package-scripts/datadog-agent#yum-source-httpsfedoraprojectorgwikipackagingscriptlets first :)
Right now, upgrading a CentOS Agent 5 to Agent6 doesn't stop the running agent 5 service.
The reason is that right now, the responsibility to stop the running service is on the `preinst` script, which on upgrade is executed on the new package. But when the new package changes the place where the service definition is (typically, when upgrading to Agent 6, which doesn't ship an `init.d` script anymore), the new package doesn't necessarily know how it should stop the existing agent (actually, the new package could anticipate that, see related PR on `datadog-agent`: …
=> [centos][prerm] Stop the agent service in prerm script

config/projects/datadog-agent.rb, resources/datadog-integrations/project.rb.erb
omnibus-ruby.
Omnibus ruby now requires that we specify the EXTRACONFS directory, rather than hard-coding.  This change matches that change (they should go in concurrently)
https://github.com/DataDog/omnibus-ruby/pull/46
=> [windows] match configuration for new generic configuration in

config/software/datadog-process-agent.rb
Currently, if we fail to grab the process agent, it won't fail. Curl doesn't error out if you get a 4xx or 5xx response code. However, it will if you pass it the option `-f`. This will make it fail noisily.
=> failure to get process agent will make the build fail

package-scripts/datadog-agent/posttrans, package-scripts/datadog-agent/preinst
This PR mirrors the work done on the Datadog Agent in this Pull Request:
https://github.com/DataDog/datadog-agent/pull/892
It makes our system user compliant with CIS 5.4.2.
=> datadog user should not be a system user

config/projects/datadog-agent.rb
with associated change https://github.com/DataDog/omnibus-ruby/pull/50 to omnibus-ruby.  Was missing some files, and was signing some files that are redistributed from other sources
=> [windows] explicitly list the files to be signed.  Used in conjunction

config/software/agent-deps.rb
Add a dependency on the prometheus-client provided [here](https://github.com/DataDog/omnibus-software/pull/172).
=> agent5: add a dependency on prometheus-client

config/projects/datadog-agent.rb, config/software/datadog-process-agent.rb, resources/datadog-agent/msi/localization-en-us.wxl.erb, resources/datadog-agent/msi/source.wxs.erb, resources/datadog-integrations/msi/source.wxs.erb
Install both APM and PRocess as an automatic start service (instead of
manual start).  Relies on the services self-stopping if they're so
configured.
Change all services to automatic restart on failure.
Move service names, descriptions, etc. into the localization file
Companion PR https://github.com/DataDog/dd-agent/pull/3655
=> [Windows] Add process agent support to agent5.

config/software/datadog-agent-integrations.rb, config/software/datadog-agent.rb
We're not shipping anything in it anymore (wheel-based build), let's
remove it to avoid confusion.
=> [unix] Remove /opt/datadog-agent/agent/checks.d directory

resources/datadog-agent/msi/source.wxs.erb
configured.  Failing to do this, however, will prevent the services from
starting on startup or upgrade even when they're preconfigured.
=> [windows] Set services to start on install; they'll stop if not

config/projects/datadog-agent.rb, package-scripts/datadog-agent/preinst
The new key is now used to sign the repo. No point in adding it in the
preinst script since a user won't be able to download the package
if the key's not already trusted on the system.
Also, remove dep on `gnupg` that came from the `apt-key` usage in
preinst script.
=> [deb] Stop adding new key

config/software/agent-deps.rb
of the other packages, but the file is required.  Will prevent this from
being inadvertently removed (and will cause it to be installed on
windows, which it's currently missing)
=> Add cacerts as an explicit dependency.  Cacerts is a dependency of some

config/software/agent-deps.rb
This was mistakenly removed in 5.22, this adds it back
=> adds nfsiostat back

config/software/datadog-agent-integrations.rb
Previous releases the PYCs were pruned in the agent definition; however, the integrations definition comes after that, and with the new wheels installation leaves a lot of PYCs around.
=> Remove PYC files after datadog-agent-integrations

config/software/datadog-agent-integrations.rb, release.json
Changes the locations of the *.yaml files to be pulled from their new location
Changes the dependency handling since we are moving to a static environment. We now install each integration with --no-deps, run a pip-compile on the agent_requirements.in file from datadog_checks_base that list the requirements for all integration and install the reqs of that compiled file.
Remove some seemingly dead code and implement the blacklist for skipping installing non-checks
We were previously doing `pip wheel --no-deps` and then pip install on that wheel. This actually causes the dependencies to still be installed, it just doesn't build the wheel for each dependency. What we want is to actually skip the deps during install, not build. 
Added a dep on pip-tools. We now compile the requirements in the …
=> Clean up integration core deps and yaml files

config/software/datadog-agent-integrations.rb
Blacklist the datadog_checks_tests-helper package from the Agent package. Its only used for running tests and dev, not required for a running agent.
=> Blacklist the datadog_checks_tests_helper package

config/software/datadog-agent.rb, files/datadog-metro/go-metro
For a better behavior on RHEL-5 boxes.
=> [datadog-metro] wrap go-metro with launcher script

config/software/datadog-agent-integrations.rb
What does this PR do?
Don't ship openstack controller
Motivation
We have a new check based on an existing check with substantial changes. This new check is still under active development and isn't currently ready to be consumer facing as its in an alpha/beta stage at the moment. Lets avoid shipping it while we have a few other breaking changes/updates/fixes in the works.
Additional Notes
Anything else we should know when reviewing?
=> Don't ship openstack_controller

config/software/datadog-agent-integrations.rb
We are only supporting this on agent 6 because of binary dependencies. I am not going to upgrade the build containers to fix this on agent 5.
=> exclude ibm_mq

config/projects/datadog-agent.rb, config/software/datadog-process-agent.rb, config/software/datadog-trace-agent.rb, release.json, resources/datadog-agent/msi/source.wxs.erb
Fixes handling of trace & process.
They were being placed in the `bin` directory prior to packaging, and then getting rolled up in the automatic collection; but they're also explicitly installed (because they're services), so they were getting installed twice.  This was destroying the reference counting.
Parallel A6 fix:  https://github.com/DataDog/datadog-agent/pull/2789
Parallel omnibus fix: https://github.com/DataDog/omnibus-ruby/pull/78
=> fix packaging of trace & process agent

config/software/agent-deps.rb
Is installed as binary wheel by integrations software def. See full context in https://github.com/DataDog/datadog-agent/pull/3160
=> [protobuf] Remove from omnibus deps of Agent

release.json
Now that `agent-v5` is the default branch for all Agentv5-related repos (except `dd-agent`, see 414db01 for explanation)
=> Point build to `agent-v5` branches by default

config/software/agent-deps.rb
Reverts DataDog/dd-agent-omnibus#361
Reason: we want `master` to contain no other change than what was in the `5.32.x` branch, so that it's still in-sync with `integrations-core`'s `agent-v5` branch. This is the only PR that was in `master` and not in `5.32.x`.
=> Revert "[protobuf] Remove from omnibus deps of Agent"

config/software/datadog-trace-agent.rb
pycurl is required, but we have a binary wheel for that. The actual curl library is not required. 
For consistency (although these definitions are actually using the builder provided curl, not the embedded one), let's use the powershell native mechanisms for downloading the deps.
=> [curl] we don't need curl on windows

release.json
Everything stays the same but branch `agent-v5` of `omnibus-software` has been updated (which makes me think that we can't have reproducible builds of the previous versions, since we pin a moving branch).
=> Add 5.32.5-rc.2 version to the release.json

config/software/pylint.rb
Alpine builds broken with newer `lazy-object-proxy`, an older version is required. 
Let's pin it here for consistency across all builds.
=> [pylint] pin lazy-object-proxy. Otherwise we have a failed build on alpine

config/software/datadog-agent-integrations.rb, config/software/datadog-trace-agent.rb, omnibus_build.sh
This PR addresses to separate issues that were causing build failures on centos and windows respectively:
- `pytest-runner` dependency pull triggered by `cisco_aci` was failing, requiring a prior manual install of the dependency.
- `dep` having issue checking out the correct revision for `github.com/openshift/api` on windows due to extraneous characters in `master` filenames (`:` to be specific). The workaround is to clone to branch `release-3.9` which contains the correct expected revision, and `dep` will skip the clone letting us get through.
=> [build] addresses build issues - required for centos + windows builds

Gemfile
Pins `aws-eventstream` and `aws-sigv4` to ruby 2.2-compatible version
Fixes:
```
Installing aws-eventstream 1.2.0
Gem::RuntimeRequirementNotMetError: aws-eventstream requires Ruby version >=
2.3. The current ruby version is 2.2.0.
An error occurred while installing aws-eventstream (1.2.0), and Bundler cannot
continue.
Make sure that `gem install aws-eventstream -v '1.2.0' --source
'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
omnibus was resolved to 5.5.0, which depends on
aws-sdk was resolved to 2.11.632, which depends on
aws-sdk-resources was resolved to 2.11.632, which depends on
aws-sdk-core was resolved to 2.11.632, which depends on
aws-sigv4 was resolved to 1.3.0, which depends on
aws-eventstream
```
(example: …
=> [Gemfile] Pin aws deps to ruby 2.2-compatible version
